trigger:
  - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: secrets

stages:
  - stage: Test
    jobs:
      - job: codebeamer
        displayName: "codebeamer upload"
        steps:
          - script: |
              echo "Empty job."
          - task: codeBeamer@1
            inputs:
              test_xml_folder: './example/test_results'
              test_run_name: '$(Build.DefinitionName) $(Build.Reason)'
              test_run_id: '$(Build.BuildId)'
              server_url: 'https://trial.codebeamer.com/cb'
              cb_user: 'laszlo.katona'
              cb_password: 'Atlas86!ntland'
              test_configuration_id: '2738877'
              test_case_tracker_id: '13186151'
              test_run_tracker_id: '13186154'