trigger:
  - master
pr:
  branches:
    include:
      - master

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: secrets

stages:
  - stage: Test
    jobs:
      - job: codebeamer
        displayName: "codebeamer upload"
        steps:
          - script: |
              echo "Empty job."
          - task: codeBeamer@1
            inputs:
              test_xml_folder: 'example/test_results'
              test_run_name: '$(Build.DefinitionName) $(Build.Reason)'
              test_run_id: '$(Build.BuildId)'
              server_url: 'https://trial.codebeamer.com/'
              cb_user: '$(cb_user)'
              cb_password: '$(cb_password)'
              test_configuration_id: '3268711'
              test_case_tracker_id: '16265191'
              test_run_tracker_id: '16265080'